### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by tiankongsang** [bet4it/shanbay2anki#1]
# 无法获取单词书

### anki版本
> 版本 2.1.29 (bbff62bf)
> Python 3.8.0 Qt 5.14.1 PyQt 5.14.1

## 问题描述
扇贝选了单词书
插件登录了账号 
点击获取直接显示例句下载完成 网络没有动静，也没有出现预期的单词书。
![image](https://user-images.githubusercontent.com/20697404/89304781-6ffa2f80-d6a0-11ea-9ef3-f2583e293852.png)

**Comment by bet4it** [comment]
之前有通过扇贝阅读添加生词吗？扇贝生词本里能看到吗？

可以把 collection.media 目录下的 shanbay2anki.log 文件贴上来。

**Comment by tiankongsang** [comment]
shanbay2anki.log 文件里有cookie 我发你gmail邮箱

**Comment by bet4it** [comment]
你生词本里就一个单词啊，还不是通过扇贝阅读添加的。

**Comment by tiankongsang** [comment]
抱歉，现在才看到wiki也写了东西的 之前就只看到 README
