### ISSUE TITLE
anki获取不到扇贝的单词

### ISSUE THREAD

**Issue by winter60** [bet4it/shanbay2anki#2]
问题：
1. 在anki里， 第一次登录了，获取不了单词。（我的扇贝里有单词书，书桌， 生词本）

![图片](https://cdn.jsdelivr.net/gh/winter60/my_figurebed/data/20201129_anki%E8%8E%B7%E5%8F%96%E4%B8%8D%E5%88%B0%E6%89%87%E8%B4%9D.gif)

**Comment by bet4it** [comment]
需要从扇贝阅读添加到生词本的才可以。你可以把扇贝APP的生词本页面截一下图

**Comment by winter60** [comment]
> 需要从扇贝阅读添加到生词本的才可以。你可以把扇贝APP的生词本页面截一下图

保存了单词在生词本里面，还是不行。 但是多了一个扇贝新闻（可能是手机上收藏了一篇文章），但anki中找不到，点了创建没反应。
![图1](https://cdn.jsdelivr.net/gh/winter60/my_figurebed/data/20201130_d67a9d35167278f5c1fc112b1d00b7a.jpg)
![图2](https://cdn.jsdelivr.net/gh/winter60/my_figurebed/data/20201130_20201130232108.png)
![图3](https://cdn.jsdelivr.net/gh/winter60/my_figurebed/data/20201130_anki%E8%8E%B7%E5%8F%96%E4%B8%8D%E5%88%B0%E6%89%87%E8%B4%9D2.gif)

**Comment by bet4it** [comment]
应该是遇到什么异常了，去anki的collection.media目录下把log文件贴出来吧，如果方便的话把db文件也贴出来

**Comment by bet4it** [comment]
也可以新建一个anki用户试一下

**Comment by winter60** [comment]
> anki的collection.media目录下把log文件
shanbay2anki.log 这这个是一个二进制文件，打不开。插件界面上的日志，我发给你看一下。

另外，新建了一个用户同样没有反应。
感谢回复。

如有需要（本人qq: 2209206864）
[扇—日志.zip](https://github.com/bet4it/shanbay2anki/files/5623092/default.zip)

**Comment by bet4it** [comment]
是这个问题：megachweng/Dict2Anki#91
Anki 版本太新了，有些地方需要做下兼容
我这几天找个时间改一下吧

**Comment by winter60** [comment]
> 是这个问题：[megachweng/Dict2Anki#91](https://github.com/megachweng/Dict2Anki/issues/91)
> Anki 版本太新了，有些地方需要做下兼容
> 我这几天找个时间改一下吧

太感谢了，想不到还能得到你的回复。

**Comment by bet4it** [comment]
😅我自己都半年没用这个插件了，不然这种问题早该发现了
你从哪知道这个插件的？Wiki 里那篇文章看过没有？

**Comment by winter60** [comment]
> 😅我自己都半年没用这个插件了，不然这种问题早该发现了
> 你从哪知道这个插件的？Wiki 里那篇文章看过没有？

我在用沙拉查词 有个同步到anki的功能不好用，模板什么的，是填空的，自己弄又太复杂。
想着有没有什么好的方法，看到下面有同步到扇贝，想着能不能通过扇贝，来同步
如果你不嫌麻烦，帮忙维护下，我想看下能不能同步，太感谢了。

**Comment by bet4it** [comment]
那你这个应用场景不对啊，我这个项目的核心是获取扇贝阅读的上下文制成单词书，你从沙拉查词导入到扇贝的肯定是没有上下文的，也就不能用我这个插件。
你可以看一下这篇文章了解我这个插件的意图：https://zhuanlan.zhihu.com/p/152597775

你这个需求应该是想办法将沙拉查词的单词导入到有道词典或者欧陆词典，然后用隔壁 [Dict2Anki](https://github.com/megachweng/Dict2Anki) 这个插件

**Comment by winter60** [comment]
> 那你这个应用场景不对啊，我这个项目的核心是获取扇贝阅读的上下文制成单词书，你从沙拉查词导入到扇贝的肯定是没有上下文的，也就不能用我这个插件。
> 你可以看一下这篇文章了解我这个插件的意图：https://zhuanlan.zhihu.com/p/152597775
> 
> 你这个需求应该是想办法将沙拉查词的单词导入到有道词典或者欧陆词典，然后用隔壁 [Dict2Anki](https://github.com/megachweng/Dict2Anki) 这个插件

那不好意思哦，（https://ankiweb.net/shared/info/775172794）看了这个插件，以为只要有单词就有上下文，浪费你回几封邮件的时间.

**Comment by bet4it** [comment]
嗯，是我太懒了，项目介绍里面应该多写点的😅

**Comment by 52086** [comment]
你好，我用此插件获取到扇贝阅读中的生词后创建单词书的时候提示如下错误，能否帮忙看看有什么解决办法没有，谢谢
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-09-08 16:13:00

File "anki/models.py", line 235, in add
File "anki/models.py", line 104, in save
File "anki/models.py", line 246, in update
File "anki/_backend/generated.py", line 488, in add_or_update_notetype
File "anki/_backend/__init__.py", line 106, in _run_command
anki.errors.InvalidInput: InvalidInput：⁨1 field required⁩
